// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgLGnNQtsUtDI2_cxJ055Zcnzq6U_Mjy0',
    appId: '1:1068880815661:web:165fcaf5ebd50ea904faa4',
    messagingSenderId: '1068880815661',
    projectId: 'scolar-chat',
    authDomain: 'scolar-chat.firebaseapp.com',
    storageBucket: 'scolar-chat.appspot.com',
    measurementId: 'G-BY0YSKZ9KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfE9Z8IowoK4oj1j_a9-aerzBJ6yJ49Ec',
    appId: '1:1068880815661:android:e86bb985edc5e3e704faa4',
    messagingSenderId: '1068880815661',
    projectId: 'scolar-chat',
    storageBucket: 'scolar-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2O9ocOnrGFb5WcuN0tX_AZwPsZO_nlVI',
    appId: '1:1068880815661:ios:da8abed769839e3d04faa4',
    messagingSenderId: '1068880815661',
    projectId: 'scolar-chat',
    storageBucket: 'scolar-chat.appspot.com',
    iosClientId: '1068880815661-ll5vs9r7dc0aqbd5vg9fetsaci29ffgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholorChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2O9ocOnrGFb5WcuN0tX_AZwPsZO_nlVI',
    appId: '1:1068880815661:ios:da8abed769839e3d04faa4',
    messagingSenderId: '1068880815661',
    projectId: 'scolar-chat',
    storageBucket: 'scolar-chat.appspot.com',
    iosClientId: '1068880815661-ll5vs9r7dc0aqbd5vg9fetsaci29ffgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholorChat',
  );
}
